/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CrashTest */

#ifndef _Included_CrashTest
#define _Included_CrashTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_legendtv_test_drivers_faults_LibCrash
 * Method:    noCrash
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_legendtv_test_drivers_faults_LibCrash_noCrash
  (JNIEnv *, jobject);

/*
 * Class:     org_legendtv_test_drivers_faults_LibCrash
 * Method:    asyncCrash
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_legendtv_test_drivers_faults_LibCrash_asyncCrash
  (JNIEnv *, jobject);

/*
 * Class:     org_legendtv_test_drivers_faults_LibCrash
 * Method:    crash
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_legendtv_test_drivers_faults_LibCrash_crash
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
